### ISSUE TITLE
Reorder section 7 to emphasize the DID Method Operations and add Create/Update details

### ISSUE THREAD

**Issue by swcurran** [trustoverip/tswg-did-method-webs-specification#101]
A simliar recommendation to @dhh1128 's comment in #97 about the document not getting to the key points.

I recommend updating section 7 so that it gets to the point, and is used as a place to explain how to actually create and update a `did:webs`.  

The reordering suggestion is to move the current `7.6 DID Method Operations` up to immediately after `7.3 Target System(s)`, moving the `Equivalent Identifiers` and `Handling Web Redirection` (which are edge cases -- important, but not fundamental).

The detail to be added is to the Create and Update subsections to describe how to create and update a `did:webs` DID.  I think the following operations should be covered:

- Create -- the inception event, including all the things that can be added at inception time, presumably:
  - set key(s), pre-rotation keys (including multi-sig)
  - set DID location
  - add services
- Update -- key rotation (including multi-sig)
- Update -- add/delete EquivID and AlsoKnowAs values
- Update -- add/delete services
- Update -- add Signed Files
- Update -- add/update Whois VP

At this point, I don't know how those actions are carried out, nor where to look to find out.

Would it be possible to explain those operations without referencing all of KERI?

**Comment by 2byrds** [comment]
@swcurran I had meant to do this with with real published examples. I am VERY close to doing that, and will use this issue as a nice outline to address it. Sorry for the delay!

**Comment by swcurran** [comment]
Cool!

**Comment by darrellodonnell** [comment]
I am going to be submitting a PR on a related issue - the simplification of some of the terminology (at minimum) and where things are being used. I believe we can get this spec to a simpler level, which I believe is good for adoption.

**Comment by 2byrds** [comment]
These sections have been significantly refactored and divided into normative/informative as well as references to the reference impl examples.
