### ISSUE TITLE
Consider verification method types for single keys

### ISSUE THREAD

**Issue by peacekeeper** [trustoverip/tswg-did-method-webs-specification#12]
In order to potentially support many key types, it may be easiest to just use the general `JsonWebKey2020` or `MultiKey` types for all verification methods in the DID document, instead of using more specific ones such as `Ed25519VerificationKey2020`.

E.g. see this sentence:
https://github.com/dhh1128/did-method-webs/blob/9c540269e87bcf47a2189bed2df5daa1973cd9ca/spec/diddocs.md?plain=1#L134

**Comment by peacekeeper** [comment]
In practical terms, does KERI currently use any key types other than Ed25519?

**Comment by dhh1128** [comment]
>In practical terms, does KERI currently use any key types other than Ed25519?

There are definitions in CESR for the goldilocks curve, but I'm not not aware of impls that use them.

I believe there *are* cases where secp256k1 is used.

**Comment by peacekeeper** [comment]
Okay. In any case, I think in the W3C community there is a clear trend towards generic `MultiKey` or `JsonWebKey` (= new name for `JsonWebKey2020`), instead of the more key-specific types.
