### ISSUE TITLE
Too much informative text; normative requirements not clear enough

### ISSUE THREAD

**Issue by talltree** [trustoverip/tswg-did-method-webs-specification#120]
This a general comment but still an important one: while the spec document contains most of the necessary material, during my review I felt as a whole it needed significant refactoring. This means three things:

1. The sections are not divided into _Normative_ and _Informative_. (As a rule, all sections up to the first normative section should be informative, and then all following sections should be normative until you get to the end matter and appendixes.)
2. It includes too much informative text; as much as possible that should be moved into:
    a. An informative introductory section that provides the necessary conceptual overview and examples to a reader before it goes into the formal normative specification sections.
    b. An appendix.
    c. An implementation guide.
    d. A separate white paper whose purpose is to provide a deeper explanation of motivations, use cases, design patterns, architectural principles, etc. that influenced the spec.
3. The normative sections need to be more carefully structured so that a developer can more easily check if their implementation meets all the MUSTs (and considers the SHOULDs and MAYs).

One specific editorial recommendation for to the third point above: **make all normative statements "human-addressable" within the spec**. This means that wherever the spec has a normative statement, do one of three things:

1. Place the normative statement entirely inside it's own unique section heading within the document.
2. Make the normative statement an item within in a numbered list within a normative section.
5. Give the normative statement an explicit "normative statement identifier", such as a unique number or label within the spec.

Following this rule, 100% of the normative statements contained in the spec can easily be referenced by:

- Other specs that build on this one.
- Conformance test plans and test suites.
- Certification reports.
- Developer documentation within implementations.

**Comment by 2byrds** [comment]
Additional notes from our Friday meeting here (i'm still trying to chase down the cloud recording): https://wiki.trustoverip.org/display/HOME/2024-01-12+did%3Awebs+Meeting+Notes

**Comment by 2byrds** [comment]
I'm still waiting for access to our meeting recording to further refine my edit strategy. But here are the first two sections we reviewed to compare the original text vs. my first draft of changes per these guidelines. Please let me know your thoughts. The grey informative section can be move to a separate document in a future PR, for now I want most of the original sentences to be present but separated per the guide:

Original text:
<img width="835" alt="image" src="https://github.com/trustoverip/tswg-did-method-webs-specification/assets/681493/8101fb4c-4287-4b44-b70d-d5dc94bdf457">

Numbered normative statement edit:
<img width="837" alt="image" src="https://github.com/trustoverip/tswg-did-method-webs-specification/assets/681493/6a73099f-be9c-487b-a99c-54ff8f79289a">
