### ISSUE TITLE
Consider adding the concept of a "handle" for a DID

### ISSUE THREAD

**Issue by swcurran** [trustoverip/tswg-did-method-webs-specification#17]
`did:plc` has the concept of a handle or a "pet name" for a DID. That is, a unique name for a DID that can be resolved in some circumstances. `did:plc` uses that for the human-friendly BluSky identifiers for people/organizations on the BluSky social network. The handle is unique and enforced by the registration of the DID with a authorized entity.

It would be interesting to see if we can add the concept of a handle to `did:webs`. A purely self-attested name (`stephen`)  would not be sufficient as it would not ensure uniqueness in any form. Perhaps we could use the "AlsoKnowAs" to remove the restriction that a `did:webs` MUST have the AID as the last part of the name.  Any web path could be a `did:webs` as long as the AID was in the DIDDoc, and the KEL/TEL was available as required by the DID Method.

**Comment by 2byrds** [comment]
We have decided that equivalentId and alsoKnownAs must be AID controlled identifiers. Should we close this @swcurran or would you like to offer alternate solutions?

**Comment by swcurran** [comment]
Happy to close and see if this comes up again.
