### ISSUE TITLE
Need a name for the KEL/TEL

### ISSUE THREAD

**Issue by swcurran** [trustoverip/tswg-did-method-webs-specification#18]
We have been making a lot of use of the term "KEL" for the file that exists beside the DIDDoc. However, as we have learned, we think it really needs to be a CESR "KEL/TEL" file. I think that we could use "CESR" as the name, but that is (AFAIU) a generic term for storing any Event Streaming data in a useful way, kind of like JSON is a generic term for storing arbitrary data in a useful kind of way.

Should we stick to "KEL/TEL", "CESR" or is there another name the is tied to KEL/TEL? Regardless, we should update the spec to be consistent throughout so it's clear when we are talking about Key Events, Transaction Events, and the KEL/TEL CESR file that contains those events.

**Comment by peacekeeper** [comment]
In https://github.com/dhh1128/did-method-webs/pull/36 we switched to the term "KERI event stream". Can we close this?

**Comment by 2byrds** [comment]
I favor the more general term 'KERI event stream' to ignore the nuance of events from KELs/TELs as well as to avoid language about files, oobis, etc. Hopefully @swcurran likes it too.

**Comment by 2byrds** [comment]
@swcurran are you happy with the "KERI event stream" that several PRs have adopted, so we can close this?

**Comment by swcurran** [comment]
Yup — I like that.
