### ISSUE TITLE
Value of "id" property in DID document on web server: did:web or did:webs

### ISSUE THREAD

**Issue by peacekeeper** [trustoverip/tswg-did-method-webs-specification#30]
One of the objectives in this work is to make sure that a did:webs can also be resolved as a did:web, e.g. the following should both be resolvable:

- `did:web:example.com:Ew-o5dU5WjDrxDBK4b4HrF82_rYb6MX6xsegjq4n0Y7M`
- `did:webs:example.com:Ew-o5dU5WjDrxDBK4b4HrF82_rYb6MX6xsegjq4n0Y7M`

Per DID specifications, the value of the "id" property in the resolved DID document must be the DID that is being resolved. In our current design however, both the did:web and did:webs methods look for the same file "did.json" at a path that corresponds to the DID. This leads to the question whether the "did.json" file that is stored on a webserver should contain a did:web "id" or a did:webs "id".

Options how to deal with this:

**1.** Introduce some kind of query parameter or HTTP header or content negotiation, to instruct the web server to either return a DID document with a did:web "id" of did:webs "id", depending on which DID method is being resolved. This has many complexities and risks I think.
**2.** Define the did:webs method such that it uses a different file, e.g. dids.json instead of did.json. The contents of dids.json and did.json would be the same, except for the "id" property. This might be acceptable, since we are already envisioning one additional file did.oobi (formerly known as did.kel) anyway, so we would just be introducing two additional files on top of what did:web does. However, this still adds some complexity and raises questions about consistency, and may lead to divergent results between did:web and did:webs resolution.
**3.** Stick with the exact did.json file used by did:web, and define even in the did:webs method specification that this file always contains the did:web DID in the DID document, to be fully compatible with the did:web method. **AND:**
**3.a.** In the did:webs method specification, we also define that at the end of the DID Resolution process (i.e. after retrieving and verifying the DID document), the did:web "id" is replaced with the did:webs "id" by the resolver. There are many other DID methods which have similar processes, i.e. where the DID document that is stored somewhere is not the "final version" that comes out of the DID Resolution function. **OR:**
**3.b.** In the did:webs method specification, we define that the DID document is actually generated by the did:webs resolver from the did.keri resource (which contains the KERI event stream), and then verified to match everything in the DID document that is retrieved from the web server, EXCEPT for the different method name. In other words, instead of first retrieving the DID document and verifying that it matches the KERI event stream found in the .keri resource, we first retrieve the .keri resource and verify that it matches the DID document, EXCEPT for the different method name.

3.a. and 3.b. have in common that on the web server side, everything is 100% compatible with did:web. The difference between 3.a. and 3.b. is only the did:webs resolution process, the end result is the same.

**Comment by dhh1128** [comment]
I think I like option 3b the best.

**Comment by swcurran** [comment]
I also like 3b.  Should we also talk about the use of AlsoKnownAs wrt to did:web and did:webs identifier.

**Comment by peacekeeper** [comment]
Yes, alsoKnownAs, controller, and other "id" properties would also be slightly different depending on whether did:web or did:webs are being resolved. Regarding the details of alsoKnownAs, we should discuss that here: https://github.com/dhh1128/did-method-webs/issues/11

**Comment by 2byrds** [comment]
I also vote 3b

**Comment by 2byrds** [comment]
From our meeting today:
@peacekeeper can you update the wording of 3b to avoid references to 'files' and instead references CESR streams from a resource that is accessible from the did:webs urn. We process the resource to verify the DID Document, including the id field.

**Comment by peacekeeper** [comment]
> can you update the wording of 3b

Done. I will work on a PR to address this in the spec early next week.
