### ISSUE TITLE
attribute more contributors or editors

### ISSUE THREAD

**Issue by dhh1128** [trustoverip/tswg-did-method-webs-specification#58]
I want more people credited on this spec than who the spec currently mentions. This is A) 100% true; and B) politically desirable. Would people mind if I submitted a PR putting other names in -- and if not, who wants to be an editor vs. a contributor?

Tagging a few people who might need to be named. @2byrds @m00sey @peacekeeper @talltree @nkongsuwan @SmithSamuelM

**Comment by swcurran** [comment]
Definitely! Please add @jljordan42 as well.

**Comment by 2byrds** [comment]
Great idea to update the list!
@SmithSamuelM should be on the editors list.
@pfeairheller should remain on the editors list for GLEIF.
@m00sey and I (@2byrds) would like to be contributors for GLEIF.
