### ISSUE TITLE
Cleanup defs and/or terminology.md

### ISSUE THREAD

**Issue by 2byrds** [trustoverip/tswg-did-method-webs-specification#78]
We have defined def:<term> throughout our documentation, and then also started to do it in terminology.md. Recommend we either shift every def:<term> to terminology.md or distribute the terms out of terminology.md and remove it.
Note there is an open PR for the terminology.md that lead to a flurry of comments https://github.com/trustoverip/tswg-did-method-webs-specification/pull/66

**Comment by swcurran** [comment]
My recommendation is to put all the `def`s in terminology.md and adjust the `ref`s in the text. When hovering over a `ref` in the text, a popup of the `def` is displayed, a click goes to the `def`.

**Comment by 2byrds** [comment]
> My recommendation is to put all the `def`s in terminology.md and adjust the `ref`s in the text. When hovering over a `ref` in the text, a popup of the `def` is displayed, a click goes to the `def`.

That seems like an ideal solution (and consistent with where the previous discussions/work was headed) @swcurran . I'll strive to adjust this as we go, and socialize it as we do passes/PRs.

**Comment by nkongsuwan** [comment]
I just submitted [PR#79](https://github.com/trustoverip/tswg-did-method-webs-specification/pull/79) to replace [PR#66](https://github.com/trustoverip/tswg-did-method-webs-specification/pull/66).

**Comment by 2byrds** [comment]
Closed by https://github.com/trustoverip/tswg-did-method-webs-specification/pull/85
