### ISSUE TITLE
How to handle multi-sig and thresholds in DIDDocs

### ISSUE THREAD

**Issue by swcurran** [trustoverip/tswg-did-method-webs-specification#8]
Research the DID Spec to see if/how multi-sig and thresholds are handled in DIDDocs. Can they be expressed?

**Comment by peacekeeper** [comment]
The W3C CCG has a work item called "ConditionalProof", which defines a verification method type that can support multi-sig and thresholds:
https://github.com/w3c-ccg/verifiable-conditions

I'm not sure if the KERI multi-sig and threshold features could be cleanly mapped to that verification method, happy to explore that further.

**Comment by dhh1128** [comment]
Do you know if this work item supports *weighted* multisig, or just standard multisig?

**Comment by peacekeeper** [comment]
Yes I think it should be possible with this: https://github.com/w3c-ccg/verifiable-conditions#weightedthreshold
