### ISSUE TITLE
Remove the “Transformations” section, or at least the “did:peer” part of it

### ISSUE THREAD

**Issue by swcurran** [trustoverip/tswg-did-method-webs-specification#83]
The `did:peer` discussion is not relevant, and should be removed.  

While the `did:peer` DID Method is extremely important, and one we should promote, the idea of “dynamic peer” DIDs has been dropped in favour of using (when needed) DID Rotation in DIDComm. `did:peer` `numalgo=0` should probably never have been introduced, as it is the (logically, at least) equivalent of the better known, commonly used and sufficient `did:key` DID Method. `numalgo=1` in theory permits key rotation, but in practice is well-under specified, and as such has never gained momentum.  `did:peer:2/3/4` are far more useful and have a future, but don’t support dynamic keys. However, they do support service endpoints and multiple keys, so a “transformation” into `did:webs` is much more challenging.

I would support removing the `transformations` section entirely, as

- the did:key transformation is self-explanatory, and no one is likely to need a “sanctioned” way to do a transformation, 
- the did:peer example is not useful to anyone

At minimum, we need to remove the `did:peer` section.

**Comment by dhh1128** [comment]
I'm fine with removing that content. I'll raise a PR if I get around to it, but don't feel that you have to wait for me.

**Comment by 2byrds** [comment]
Closed by https://github.com/trustoverip/tswg-did-method-webs-specification/pull/84
