### ISSUE TITLE
Full Example section paragraph is difficult for a newbie to parse and match with JSON

### ISSUE THREAD

**Issue by edeykholt** [trustoverip/tswg-did-method-webs-specification#86]
I attempted to rewrite this paragraph, but didn't understand it clearly enough to complete this.  

It currently reads as follows:
`The following blocks contain full annotated examples of a KERI AID with two events, an inception event and an interaction event, some witnesses, multiple public signing and rotation keys and an Agent with the resulting DID document that an implementation would generate assuming the implementation was running on the `example.com` domain with no unique port and no additional path defined:
`
It would be helpful to enumerate each section during the introduction, such as:
`The following blocks [in the ?XX?] contain full annotated examples of a KERI AID with 1) an inception event (icp) with ...; 2) an interaction event (ixn) with ...; 3) ....; 4); ... and 5) ...`

**Comment by 2byrds** [comment]
The full example has been significantly refactored into singular examples and many informative sections within the annex
