### ISSUE TITLE
why must FQDN not include IP addresses?

### ISSUE THREAD

**Issue by dhh1128** [trustoverip/tswg-did-method-webs-specification#98]
I have a negative reaction to this statement: "The fully qualified domain MUST NOT include IP addresses" which occurs [here](https://trustoverip.github.io/tswg-did-method-webs-specification/index.html#method-specific-identifier). I wrote the first draft of this particular section, and I remember copying this sentence from the did:web spec, so I assume that's why the sentence exists. In did:web, it was justified by the idea that security was tied to certificates, and certificates wouldn't be issued to IP addresses. Thus, having a FQDN that's an IP address would introduce unnecessary caveats to the method.

This is not true of did:webs. We lose no security by allowing a FQDN to be an IP address, and we gain quite a lot of flexibility. In a world where IPv6 is ubiquitous, that flexibility might be valuable. We could publish did:webs docs on a mobile phone, for example.

The counter argument that I'm aware of is that we want to keep this sentence so did:webs and did:web remain as similar as possible. That is, we want to prevent did:webs DIDs from being published in places where did:web DIDs can't also be published.

This feels irrational to me. Any places that are capable of publishing a did:web DID can also publish a did:webs DID, so being more flexible in did:webs sacrifices zero in terms of an upgrade path. And we are trying to provide a one-way upgrade path, not a two-way equivalence, are we not? What the flexibility does sacrifice is the guarantee that every did:webs can also be viewed as a did:web; there could be corner cases where that is not true (that is, the equivalence is not perfect in both directions). But those corner cases are unlikely to be interesting to people who want did:web support, anyway (who would try to publish a corporation's did:web/did:webs on a cell phone running IPv6?).

My preference, therefore, is to simply remove this one sentence.

If the will of the team is to keep it, because of the compatibility argument, then my fallback recommendation is to at least justify the sentence with an explanation: "To maximize similarity with did:web, which depends on certificate security, the fully qualified domain MUST NOT include IP addresses."

**Comment by 2byrds** [comment]
I think did:webs as a super-set of did:web functionalities is consistent with our direction. I agree with @dhh1128

**Comment by 2byrds** [comment]
Closed by PR https://github.com/trustoverip/tswg-did-method-webs-specification/pull/99
